### ISSUE TITLE
Ignore folder?

### ISSUE THREAD

**Issue by yovanoc** [PabloSzx/bob-esbuild#149]
Hello,
I have a monorepo with PNPM and bob-esbuild. Now I try to add a nextjs app inside of it and I get a lot of errors that's come from the next app when I build with bob at the root. I think we have to ignore this app but I don't know where? thanks for the upcoming advice to do that

**Comment by PabloSzx** [comment]
bob-esbuild is opt-in rather than opt-out, and if you are referring to the typescript types step you can simply add the ignore app in the "exclude" of your root tsconfig.json
