### ISSUE TITLE
Typescript path expansion support

### ISSUE THREAD

**Issue by ccollie** [PabloSzx/bob-esbuild#156]
Im developing a library which internally leverages `ts` path mappings, but I don't want to impose the use of a node alias mapper on the end user.

I ran across this tool: https://github.com/justkey007/tsc-alias , so someone had the same idea. It seems to me that it would be a great addition to `bob-ts` since my use-case seems common.

**Comment by PabloSzx** [comment]
This is available in bob-esbuild@3.0.0 with a new flag in the global configuration:

```ts
export const config: import('bob-esbuild').BobConfig = {
  // ...
  useTsconfigPaths: true,
};

````

**Comment by PabloSzx** [comment]
Added this feature to `bob-ts` as well, bob-ts@1.2.0 with "--paths" flag / config

**Comment by ccollie** [comment]
Thanks a millions @PabloSzx
